In [41]:
import numpy as np
import pandas as pd
from matplotlib.image import imread

## Datatypes and Attributes

In [42]:
a = np.array([1, 2, 3, 4, 5])
a

array([1, 2, 3, 4, 5])

In [43]:
a1 = np.array([[1, 2, 3],
               [6, 6, 8]])
a1

array([[1, 2, 3],
       [6, 6, 8]])

In [44]:
print(a)

[1 2 3 4 5]


In [45]:
a2 = np.array([[[1, 2, 3],
                [6, 7, 8]],
              
              [[1, 2, 3],
               [6, 7, 8]]])

In [46]:
a2

array([[[1, 2, 3],
        [6, 7, 8]],

       [[1, 2, 3],
        [6, 7, 8]]])

In [47]:
# print(a2.shape)
# print(a2)

In [48]:
a2.size

12

In [49]:
df = pd.DataFrame(a1)
df

0  1  2
0  1  2  3
1  6  6  8

## Messive Array

In [50]:
messive_array = np.random.random(100)
messive_array

array([0.26455561, 0.77423369, 0.45615033, 0.56843395, 0.0187898 ,
       0.6176355 , 0.61209572, 0.616934  , 0.94374808, 0.6818203 ,
       0.3595079 , 0.43703195, 0.6976312 , 0.06022547, 0.66676672,
       0.67063787, 0.21038256, 0.1289263 , 0.31542835, 0.36371077,
       0.57019677, 0.43860151, 0.98837384, 0.10204481, 0.20887676,
       0.16130952, 0.65310833, 0.2532916 , 0.46631077, 0.24442559,
       0.15896958, 0.11037514, 0.65632959, 0.13818295, 0.19658236,
       0.36872517, 0.82099323, 0.09710128, 0.83794491, 0.09609841,
       0.97645947, 0.4686512 , 0.97676109, 0.60484552, 0.73926358,
       0.03918779, 0.28280696, 0.12019656, 0.2961402 , 0.11872772,
       0.31798318, 0.41426299, 0.0641475 , 0.69247212, 0.56660145,
       0.26538949, 0.52324805, 0.09394051, 0.5759465 , 0.9292962 ,
       0.31856895, 0.66741038, 0.13179786, 0.7163272 , 0.28940609,
       0.18319136, 0.58651293, 0.02010755, 0.82894003, 0.00469548,
       0.67781654, 0.27000797, 0.73519402, 0.96218855, 0.24875

In [51]:
messive_array[:50]

array([0.26455561, 0.77423369, 0.45615033, 0.56843395, 0.0187898 ,
       0.6176355 , 0.61209572, 0.616934  , 0.94374808, 0.6818203 ,
       0.3595079 , 0.43703195, 0.6976312 , 0.06022547, 0.66676672,
       0.67063787, 0.21038256, 0.1289263 , 0.31542835, 0.36371077,
       0.57019677, 0.43860151, 0.98837384, 0.10204481, 0.20887676,
       0.16130952, 0.65310833, 0.2532916 , 0.46631077, 0.24442559,
       0.15896958, 0.11037514, 0.65632959, 0.13818295, 0.19658236,
       0.36872517, 0.82099323, 0.09710128, 0.83794491, 0.09609841,
       0.97645947, 0.4686512 , 0.97676109, 0.60484552, 0.73926358,
       0.03918779, 0.28280696, 0.12019656, 0.2961402 , 0.11872772])

In [52]:
a1.reshape(2,3,1)

array([[[1],
        [2],
        [3]],

       [[6],
        [6],
        [8]]])

In [53]:
a1.shape

(2, 3)

In [54]:
a1*a2

array([[[ 1,  4,  9],
        [36, 42, 64]],

       [[ 1,  4,  9],
        [36, 42, 64]]])

In [55]:
a.reshape(5,1)

array([[1],
       [2],
       [3],
       [4],
       [5]])

In [56]:
a.shape

(5,)

In [57]:
a.T

array([1, 2, 3, 4, 5])

In [58]:
a.shape

(5,)

In [59]:
c = [[1, 0],
     [0, 1]]


b = [[4, 1],
     [2, 2]]

In [60]:
np.dot(c, b)

array([[4, 1],
       [2, 2]])

In [61]:
# numpy official documentation example
c = np.arange(3*4*5*6).reshape((3,4,5,6))
b = np.arange(3*4*5*6)[::-1].reshape((5,4,6,3))
np.dot(c, b)[2,3,2,1,2,2]

499128

## DOT PRODUCT

In [62]:
np.random.seed(0)


mat1 = np.random.randint(10, size=(5, 3))
mat2 = np.random.randint(10, size=(5, 3))


print("Matrix 1: \n", mat1)
print()
print("Matrix 2: \n", mat2)

Matrix 1: 
 [[5 0 3]
 [3 7 9]
 [3 5 2]
 [4 7 6]
 [8 8 1]]

Matrix 2: 
 [[6 7 7]
 [8 1 5]
 [9 8 9]
 [4 3 0]
 [3 5 0]]


In [63]:
mat2

array([[6, 7, 7],
       [8, 1, 5],
       [9, 8, 9],
       [4, 3, 0],
       [3, 5, 0]])

In [64]:
# element wise multiplication
mat1*mat2

array([[30,  0, 21],
       [24,  7, 45],
       [27, 40, 18],
       [16, 21,  0],
       [24, 40,  0]])

In [65]:
mat1 = mat1.T

In [66]:
np.dot(mat1, mat2)

array([[121, 114,  77],
       [153, 108,  80],
       [135,  69,  84]])

## Sort NumPy array

In [67]:
random_a = np.random.randint(10, size=(5, 3))

In [68]:
random_a

array([[2, 3, 8],
       [1, 3, 3],
       [3, 7, 0],
       [1, 9, 9],
       [0, 4, 7]])

In [69]:
np.sort(random_a)

array([[2, 3, 8],
       [1, 3, 3],
       [0, 3, 7],
       [1, 9, 9],
       [0, 4, 7]])

In [70]:
np.argsort(random_a)

array([[0, 1, 2],
       [0, 1, 2],
       [2, 0, 1],
       [0, 1, 2],
       [0, 1, 2]], dtype=int64)

## Numpy in Action Converting images into numpy array

In [71]:
panda = imread("images/panda.png")

In [72]:
panda

array([[[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       [[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       [[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       ...,

       [[0.13333334, 0.07450981, 0.05490196],
        [0.12156863, 0.0627451 , 0.04313726],
        [0.10980392, 0

In [73]:
car = imread("images/car-photo.png")
car

array([[[0.5019608 , 0.50980395, 0.4862745 , 1.        ],
        [0.3372549 , 0.34509805, 0.30588236, 1.        ],
        [0.20392157, 0.21568628, 0.14901961, 1.        ],
        ...,
        [0.64705884, 0.7058824 , 0.54901963, 1.        ],
        [0.59607846, 0.63529414, 0.45882353, 1.        ],
        [0.44705883, 0.47058824, 0.3372549 , 1.        ]],

       [[0.44313726, 0.43529412, 0.40392157, 1.        ],
        [0.3137255 , 0.31764707, 0.27450982, 1.        ],
        [0.2       , 0.21176471, 0.14117648, 1.        ],
        ...,
        [0.5058824 , 0.5372549 , 0.4117647 , 1.        ],
        [0.49803922, 0.52156866, 0.39607844, 1.        ],
        [0.4       , 0.42745098, 0.34117648, 1.        ]],

       [[0.39607844, 0.38039216, 0.34117648, 1.        ],
        [0.31764707, 0.3137255 , 0.27450982, 1.        ],
        [0.28627452, 0.29411766, 0.24705882, 1.        ],
        ...,
        [0.44705883, 0.45882353, 0.32156864, 1.        ],
        [0.45882353, 0.482352

In [74]:
dog = imread("images/dog-photo.png")
dog

array([[[0.70980394, 0.80784315, 0.88235295, 1.        ],
        [0.72156864, 0.8117647 , 0.8862745 , 1.        ],
        [0.7411765 , 0.8156863 , 0.8862745 , 1.        ],
        ...,
        [0.49803922, 0.6862745 , 0.8392157 , 1.        ],
        [0.49411765, 0.68235296, 0.8392157 , 1.        ],
        [0.49411765, 0.68235296, 0.8352941 , 1.        ]],

       [[0.69411767, 0.8039216 , 0.8862745 , 1.        ],
        [0.7019608 , 0.8039216 , 0.88235295, 1.        ],
        [0.7058824 , 0.80784315, 0.88235295, 1.        ],
        ...,
        [0.5019608 , 0.6862745 , 0.84705883, 1.        ],
        [0.49411765, 0.68235296, 0.84313726, 1.        ],
        [0.49411765, 0.68235296, 0.8392157 , 1.        ]],

       [[0.6901961 , 0.8       , 0.88235295, 1.        ],
        [0.69803923, 0.8039216 , 0.88235295, 1.        ],
        [0.7058824 , 0.80784315, 0.88235295, 1.        ],
        ...,
        [0.5019608 , 0.6862745 , 0.84705883, 1.        ],
        [0.49803922, 0.686274

In [78]:
# <img src="images/me.jpeg"/>

SyntaxError: invalid syntax (Temp/ipykernel_8288/1571944990.py, line 1)

In [79]:
me = imread("images/me.jpeg")
me

array([[[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       ...,

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]]