In [1]:
import numpy as np
import pandas as pd
from matplotlib.image import imread

In [3]:
# Create a 1-dimensional NumPy array using np.array()

one_d = np.array([1, 2, 3, 4, 5, 6])
one_d

array([1, 2, 3, 4, 5, 6])

In [4]:
# Create a 2-dimensional NumPy array using np.array()

two_d = np.array([[1, 2, 3],
                  [4, 5, 6]])
two_d

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
# Create a 3-dimensional Numpy array using np.array()

three_d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
three_d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
# Attributes of 1-dimensional array (shape, 
# number of dimensions, data type, size and type)


print("1-d: ", one_d.shape, one_d.ndim, one_d.dtype, one_d.size)
print("2-d: ", two_d.shape, two_d.ndim, two_d.dtype, two_d.size)
print("3-d: ",three_d.shape, three_d.ndim, three_d.dtype, three_d.size)

1-d:  (6,) 1 int32 6
2-d:  (2, 3) 2 int32 6
3-d:  (3, 3) 2 int32 9


In [10]:
# Import pandas and create a DataFrame out of one
# of the arrays you've created


df = pd.DataFrame(three_d)

In [12]:
df

0  1  2
0  1  2  3
1  4  5  6
2  7  8  9

In [17]:
# Create an array of shape (10, 2) with only ones

ones_only = np.ones((10, 5))
ones_only

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [20]:
# Create an array of shape (7, 2, 3) of only zeros

zeros_only = np.zeros((7, 2, 3))

In [19]:
zeros_only

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [24]:
# Create an array within a range of 0 and 100 with step 3

random_array = np.arange(0, 100, 3)
random_array

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [27]:
# Create a random array with numbers between 0 and 10 of size (7, 2)
rand_array = np.random.randint(11, size=(7, 2))

In [28]:
rand_array

array([[ 1,  7],
       [10, 10],
       [ 3, 10],
       [ 0,  8],
       [ 9,  6],
       [ 7,  4],
       [ 5,  2]])

In [40]:
# Create a random array of floats between 0 & 1 of shape (3, 5)

random_floats = np.random.sample((7, 3))

In [37]:
random_floats

array([[0.93737308, 0.32802867, 0.67201801],
       [0.57056193, 0.42362281, 0.32146073],
       [0.26217088, 0.50337606, 0.07923804],
       [0.85504092, 0.95381706, 0.00351733],
       [0.88088499, 0.21302178, 0.85385015],
       [0.53248733, 0.22661206, 0.44487341],
       [0.63088994, 0.5452078 , 0.0974377 ]])

In [46]:
# Set the random seed to 42
np.random.seed(42)


# Create a random array of numbers between 0 & 10 of size (4, 6)
arr = np.random.randint(10, size=(4, 6))
arr

array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]])

In [51]:
# Create an array of random numbers between 1 & 10 of size (3, 7)
# and save it to a variable
aar_1 = np.random.randint(10, size=(3, 7))
print(aar_1)


# Find the unique numbers in the array you just created
np.unique(aar_1)

[[5 2 0 2 4 2 0]
 [4 9 6 6 8 9 9]
 [2 6 0 3 3 4 6]]


array([0, 2, 3, 4, 5, 6, 8, 9])